### ISSUE TITLE
Corners don't work

### ISSUE THREAD

**Issue by tommycli** [paulswartz/gnome-shell-grid#7]
Corners don't work with traceback:

```
Traceback (most recent call last):
  File "gnome-shell-grid.py", line 180, in <module>
    main()
  File "gnome-shell-grid.py", line 172, in main
    g = func(w, (root_width, root_height), (x, y, width, height))
  File "gnome-shell-grid.py", line 25, in wrapper
    possible_positions = func((width, height))
  File "gnome-shell-grid.py", line 14, in wrapper
    if w.is_maximized():
AttributeError: 'tuple' object has no attribute 'is_maximized'
```

See my pull request for a proposed fix.

**Comment by tommycli** [comment]
Oops duplicated during pull request.
